import test from 'node:test';import assert from 'node:assert/strict';
import {HandTracker,mapPoint,assign,smooth,describeHand} from '../app/core.mjs';
const hand=(x,y=.5)=>({x,y,size:.1,handedness:'Left',pinch:.7,fingers:[1,1,1,1],fist:false});
test('mirrored calibrated mapping reaches edges and clamps',()=>{assert.deepEqual(mapPoint({x:.9,y:.15}),{x:0,y:0});const p=mapPoint({x:.1,y:.85});assert.ok(Math.abs(p.x-1)<1e-10);assert.equal(p.y,1);assert.deepEqual(mapPoint({x:-2,y:9}),{x:1,y:1});});
test('assignment avoids greedy ID swaps and unreachable jumps',()=>{assert.deepEqual(assign([[.1,.11],[.12,Infinity]]),[1,0]);assert.deepEqual(assign([[Infinity]]),[-1]);});
test('frame order does not change identity; disappearance reserves ownership',()=>{const t=new HandTracker();t.update([hand(.2),hand(.8)],0);const ids=t.tracks.map(t=>t.id);t.update([hand(.79),hand(.21)],50);assert.deepEqual(t.tracks.map(t=>t.id),ids);assert.equal(t.tracks[0].x,.21);t.update([],150);assert.equal(t.tracks[0].state,'hold');t.update([],500);assert.equal(t.tracks[0].state,'lost');t.update([],9000);assert.equal(t.tracks.length,2);assert.ok(t.tracks.every(t=>t.state==='dormant'));});
test('overlap freezes instead of spawning two substitute identities',()=>{const t=new HandTracker();t.update([hand(.4),hand(.6)],0);t.update([hand(.49),hand(.51)],60);assert.equal(t.tracks.length,2);assert.ok(t.tracks.every(t=>t.state==='hold'));});
test('ten slots cap; explicit reset frees bindings; pinch hysteresis',()=>{const t=new HandTracker();const hs=Array.from({length:10},(_,i)=>hand(.08+(i%5)*.2,.2+Math.floor(i/5)*.6));t.update(hs,0);assert.equal(t.tracks.length,10);assert.equal(new Set(t.tracks.map(t=>t.slot)).size,10);t.update([...hs,hand(.5)],50);assert.equal(t.tracks.length,10);t.update([],1700);assert.equal(t.tracks.length,10);t.reset();t.update([{...hand(.5),pinch:.2}],1750);assert.equal(t.tracks[0].slot,0);assert.equal(t.tracks[0].pinched,true);t.update([{...hand(.5),pinch:.35}],1800);assert.equal(t.tracks[0].pinched,true);t.update([{...hand(.5),pinch:.5}],1850);assert.equal(t.tracks[0].pinched,false);});
test('smoothing is frame-rate independent and invalid landmarks are rejected',()=>{const one=smooth(0,1,100);const two=smooth(smooth(0,1,50),1,50);assert.ok(Math.abs(one-two)<1e-12);assert.equal(describeHand([]),null);});
