const $=s=>document.querySelector(s), KEY='ahalab-butterfly-garden-v1';
const MAPS=[{id:'meadow',name:'晴天草地',icon:'✿',friends:0,care:0,spots:['花丛后面','大树旁边','草堆里面']},{id:'forest',name:'小小树林',icon:'♠',friends:2,care:4,spots:['树洞旁边','落叶下面','树丛后面']},{id:'lake',name:'弯弯池塘',icon:'≈',friends:5,care:12,spots:['芦苇里面','小桥旁边','石头后面']},{id:'snow',name:'软软雪地',icon:'❄',friends:8,care:20,spots:['雪堆后面','松树旁边','冰块后面']}];
const ANIMALS=[
 {id:'cat',species:'小猫',map:0,color:'#e7ae75',light:'#fff0d8',kind:'cat',food:'小猫粮',snack:'●'},
 {id:'rabbit',species:'兔子',map:0,color:'#f6eadb',light:'#fffaf0',kind:'rabbit',food:'兔兔草饼',snack:'♧'},
 {id:'dog',species:'小狗',map:0,color:'#bb946e',light:'#f9e6cb',kind:'dog',food:'小狗粮',snack:'●'},
 {id:'fox',species:'小狐狸',map:1,color:'#d58a55',light:'#fff0d9',kind:'fox',food:'狐狸小餐',snack:'◒'},
 {id:'hedgehog',species:'小刺猬',map:1,color:'#a8876f',light:'#edceb0',kind:'hedgehog',food:'刺猬小餐',snack:'●'},
 {id:'deer',species:'小鹿',map:1,color:'#cda277',light:'#fff0d6',kind:'deer',food:'嫩叶',snack:'♧'},
 {id:'otter',species:'小水獭',map:2,color:'#ab8c71',light:'#f2ddbc',kind:'otter',food:'小鱼餐',snack:'⋈'},
 {id:'duck',species:'小鸭子',map:2,color:'#edcf7a',light:'#fff1bd',kind:'duck',food:'鸭鸭谷粒',snack:'⁙'},
 {id:'capybara',species:'水豚',map:2,color:'#b6997b',light:'#dac0a0',kind:'capybara',food:'青草',snack:'♧'},
 {id:'penguin',species:'小企鹅',map:3,color:'#6d8388',light:'#f7f1dd',kind:'penguin',food:'小鱼餐',snack:'⋈'},
 {id:'bear',species:'小白熊',map:3,color:'#edf0e8',light:'#fffdf3',kind:'bear',food:'白熊小餐',snack:'◒'},
 {id:'snowfox',species:'小雪狐',map:3,color:'#e8e9e5',light:'#ffffff',kind:'fox',food:'雪狐小餐',snack:'◒'}
];
const freshPet=()=>({name:'',full:40,happy:45,bond:0});
const fresh=()=>({version:1,pets:{cat:freshPet()},selected:'cat',map:0,care:0,sound:true});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version!==1||!x.pets||typeof x.pets!=='object')return fresh();const pets={};for(const a of ANIMALS){const p=x.pets[a.id];if(p&&typeof p==='object')pets[a.id]={name:typeof p.name==='string'?p.name.slice(0,12):'',full:Number.isFinite(p.full)?Math.max(0,Math.min(100,p.full)):40,happy:Number.isFinite(p.happy)?Math.max(0,Math.min(100,p.happy)):45,bond:Number.isFinite(p.bond)?Math.max(0,Math.min(6,p.bond)):0}}if(!pets.cat)pets.cat=freshPet();return {version:1,pets,selected:pets[x.selected]?x.selected:'cat',map:Number.isInteger(x.map)&&x.map>=0&&x.map<4?x.map:0,care:Number.isFinite(x.care)?Math.max(0,Math.floor(x.care)):0,sound:x.sound!==false}}catch{return fresh()}}
let state=load(),mode='home',busy=false,resetPending=false,audio;
const selected=()=>ANIMALS.find(a=>a.id===state.selected), pet=()=>state.pets[state.selected], displayName=a=>state.pets[a.id]?.name||a.species;
const unlocked=m=>Object.keys(state.pets).length>=m.friends&&state.care>=m.care;
if(!unlocked(MAPS[state.map]))state.map=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-note').textContent='进度保存在这台设备的浏览器里。'}catch{$('#save-note').textContent='浏览器没有保存成功，先别关闭这个页面。';say('这次进度还在，但浏览器没有保存成功。请先别关闭页面。')}}
function say(text){$('#message').textContent=text}
function tone(kind){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='find'?[523,659,784]:kind==='play'?[440,659,554]:[523,659];notes.forEach((hz,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.11;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.055,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.21)})}catch{}}
function svg(a){const c=a.color,l=a.light,k=a.kind;let ears='',tail='',extra='',head='<ellipse cx="100" cy="99" rx="48" ry="43" fill="'+c+'"/>';
 if(['cat','fox'].includes(k)){ears=`<path d="M55 81 L55 32 Q78 38 88 63 M112 63 Q135 38 147 33 L146 85" fill="${c}"/><path d="M62 65 L62 45 79 63 M121 63 140 46 139 69" fill="#dfb2a0"/>`;tail=`<path class="tail" d="M130 161 Q188 177 166 113" fill="none" stroke="${c}" stroke-width="24" stroke-linecap="round"/>`}
 else if(k==='rabbit')ears=`<ellipse cx="77" cy="45" rx="14" ry="39" fill="${c}" transform="rotate(-10 77 45)"/><ellipse cx="121" cy="44" rx="14" ry="39" fill="${c}" transform="rotate(9 121 44)"/><ellipse cx="77" cy="43" rx="6" ry="26" fill="#e7b8ae"/><ellipse cx="121" cy="41" rx="6" ry="26" fill="#e7b8ae"/>`;
 else if(k==='dog')ears=`<ellipse cx="53" cy="91" rx="19" ry="37" fill="#92704f" transform="rotate(17 53 91)"/><ellipse cx="146" cy="91" rx="19" ry="37" fill="#92704f" transform="rotate(-17 146 91)"/>`;
 else if(k==='deer'){ears=`<path d="M69 65 Q29 29 40 70 L64 82 M131 65 Q171 29 160 70 L136 82" fill="${c}"/><path d="M76 64 65 29 M67 40 54 34 M123 64 134 29 M132 40 145 34" stroke="#977452" stroke-width="7" stroke-linecap="round"/>`;extra='<g fill="#fff1db"><circle cx="73" cy="90" r="4"/><circle cx="127" cy="90" r="4"/><circle cx="86" cy="75" r="3"/><circle cx="113" cy="75" r="3"/></g>'}
 else if(!['duck','penguin'].includes(k))ears=`<circle cx="63" cy="65" r="18" fill="${c}"/><circle cx="138" cy="65" r="18" fill="${c}"/><circle cx="63" cy="65" r="10" fill="#d6b7a1"/><circle cx="138" cy="65" r="10" fill="#d6b7a1"/>`;
 if(k==='hedgehog'){tail=`<path d="M48 165 25 147 34 127 19 111 37 91 30 68 54 63 60 40 84 47 101 26 119 47 145 40 148 65 170 70 162 94 180 109 163 126 174 149 150 169Z" fill="#8c7865"/>`;ears=''}
 if(k==='penguin')head+=`<path d="M63 91 Q67 59 100 84 Q133 59 137 91 L136 119 Q100 148 64 119Z" fill="${l}"/>`;
 const beak=['duck','penguin'].includes(k), nose=beak?'<ellipse cx="100" cy="112" rx="14" ry="8" fill="#dfa04d"/>':'<path d="M94 107 Q100 103 106 107 Q100 116 94 107" fill="#87635b"/>';
 return `<svg class="animal-svg" viewBox="0 0 200 210" aria-hidden="true">${tail}<ellipse cx="100" cy="152" rx="49" ry="43" fill="${c}"/><ellipse cx="100" cy="158" rx="29" ry="30" fill="${l}"/><ellipse cx="68" cy="183" rx="20" ry="12" fill="${c}"/><ellipse cx="132" cy="183" rx="20" ry="12" fill="${c}"/>${ears}${head}${k==='fox'?`<path d="M54 98 Q72 132 100 132 Q128 132 146 98 Q119 100 100 114 Q82 99 54 98" fill="${l}"/>`:''}${['dog','bear','otter','capybara'].includes(k)?`<ellipse cx="100" cy="112" rx="25" ry="18" fill="${l}"/>`:''}${extra}<g class="eyes" fill="#35473c"><ellipse cx="80" cy="96" rx="4.3" ry="5.7"/><ellipse cx="120" cy="96" rx="4.3" ry="5.7"/></g><g fill="#e2a393" opacity=".55"><ellipse cx="65" cy="109" rx="8" ry="4"/><ellipse cx="135" cy="109" rx="8" ry="4"/></g>${nose}<path class="mouth" d="M92 118 Q100 125 108 118" fill="none" stroke="#866d5b" stroke-width="2.4" stroke-linecap="round"/>${k==='cat'?'<path d="M51 110 70 113 M49 118 69 118 M130 113 149 110 M131 118 151 118" stroke="#9d7a59" stroke-width="1.7"/>':''}<path d="M57 144 Q47 157 56 166 M143 144 Q153 157 144 166" fill="none" stroke="${c}" stroke-width="15" stroke-linecap="round"/></svg>`;
}
function render(){
 $('.intro').textContent=Object.keys(state.pets).length===1&&!pet().name?'小猫在等你。先给它起个名字吧。':'选一只动物陪它玩，或去地图里找新朋友。';
 const a=selected(),p=pet();$('#friend-count').textContent=Object.keys(state.pets).length;$('#care-count').textContent=state.care;
 $('#map-list').replaceChildren();MAPS.forEach((m,i)=>{const open=unlocked(m),count=ANIMALS.filter(a=>a.map===i&&state.pets[a.id]).length,b=document.createElement('button');b.className='map-button'+(state.map===i?' active':'')+(!open?' locked':'');b.dataset.map=i;b.setAttribute('aria-pressed',state.map===i);b.setAttribute('aria-label',m.name+(open?'':'，还没开放'));b.innerHTML=`<span class="map-icon">${m.icon}</span><span><b>${m.name}</b><small>${open?`找到 ${count} / 3 只`:`${m.friends}只朋友 · 照顾${m.care}次`}</small></span>`;b.onclick=()=>{if(busy)return;if(!open){say(`${m.name}还没开放。再找到${Math.max(0,m.friends-Object.keys(state.pets).length)}只动物，再喂食或玩耍${Math.max(0,m.care-state.care)}次就可以去。`);return}state.map=i;mode='explore';save();render();say(`到了${m.name}，点点藏身处，看看谁在里面。`)};$('#map-list').append(b)});
 const next=MAPS.find(m=>!unlocked(m));$('#unlock-tip').textContent=next?`下一站：${next.name}。找到${next.friends}只动物，累计喂食或玩耍${next.care}次。`:'四张地图都开放了！找齐朋友后，还可以回来陪它们玩。';
 $('#place-label').textContent=`0${state.map+1} / ${MAPS[state.map].name}`;$('#scene-title').textContent=mode==='home'?`和${displayName(a)}待一会儿`:'谁藏在这里？';$('#scene').className=`scene ${MAPS[state.map].id}${mode==='explore'?' exploring':''}`;$('#home-mode').setAttribute('aria-pressed',mode==='home');$('#explore-mode').setAttribute('aria-pressed',mode==='explore');$('#scene-hint').textContent=mode==='home'?'点点小动物，跟它打个招呼':'点花丛、树丛或石头，找找小动物';
 $('#pet-name').textContent=displayName(a);$('#species-label').textContent=`我的${a.species}`;$('#name-input').value=p.name;$('#pet-body').innerHTML=svg(a);$('#pet-body').setAttribute('aria-label',`摸摸${displayName(a)}`);$('#food-label').textContent=a.food;$('#full').value=p.full;$('#happy').value=p.happy;$('#full-text').textContent=p.full>=85?'饱饱的':p.full>=60?'吃得不错':'还能吃一点';$('#happy-text').textContent=p.happy>=85?'很开心':p.happy>=60?'心情不错':'想和你玩';$('#bond').textContent='♥'.repeat(Math.min(3,Math.floor(p.bond/2)))+'♡'.repeat(3-Math.min(3,Math.floor(p.bond/2)));$('#bond').setAttribute('aria-label',`熟悉程度${Math.min(3,Math.floor(p.bond/2))}颗心，共3颗`);
 $('#search-spots').replaceChildren();if(mode==='explore')ANIMALS.filter(a=>a.map===state.map).forEach((a,i)=>{const found=!!state.pets[a.id],b=document.createElement('button');b.className='search-spot'+(found?' found':'');b.dataset.animal=a.id;b.setAttribute('aria-label',MAPS[state.map].spots[i]+(found?'，已经找到'+a.species:'，找一找'));b.innerHTML=`<svg viewBox="0 0 110 80" aria-hidden="true"><ellipse cx="55" cy="70" rx="42" ry="8" fill="#53734d22"/><path d="M12 64 Q-2 38 25 37 Q18 4 49 21 Q66 0 81 27 Q108 24 100 51 Q112 72 75 69 L33 69Z" fill="${state.map===3?'#eaf1ee':state.map===1?'#789675':'#8fac79'}"/><path d="M29 53 37 42 M60 42 65 29 M80 58 86 47" stroke="${state.map===3?'#c6d8d8':'#b7ca99'}" stroke-width="4" stroke-linecap="round"/><text x="54" y="56" text-anchor="middle" font-size="22" fill="#fff9e8">${found?'✓':'?'}</text></svg><span>${found?a.species:MAPS[state.map].spots[i]}</span>`;b.onclick=()=>discover(a);$('#search-spots').append(b)});
 $('#animal-list').replaceChildren();for(const a of ANIMALS){const own=!!state.pets[a.id],b=document.createElement('button');b.className='animal-card'+(own?'':' locked')+(state.selected===a.id?' selected':'');b.dataset.pet=a.id;b.setAttribute('aria-pressed',state.selected===a.id);b.setAttribute('aria-label',own?`选择${displayName(a)}`:`未找到的动物，住在${MAPS[a.map].name}`);b.innerHTML=own?svg(a):'<span class="unknown">?</span>';const label=document.createElement('span');label.className='animal-label';label.textContent=own?displayName(a):'还没见过';b.append(label);const small=document.createElement('small');small.textContent=own?a.species:MAPS[a.map].name;b.append(small);b.onclick=()=>{if(busy)return;if(!own){say(`它住在${MAPS[a.map].name}，去那里找找吧。`);return}state.selected=a.id;mode='home';save();render();say(`${displayName(a)}来了！今天想喂它，还是陪它玩？`)};$('#animal-list').append(b)}
 $('#sound').textContent=state.sound?'♪ 声音开':'♪ 声音关';$('#sound').setAttribute('aria-pressed',state.sound);
}
function discover(a){if(busy)return;if(state.pets[a.id]){say(`这里已经找到了${displayName(a)}。试试另外的藏身处。`);return}state.pets[a.id]=freshPet();state.selected=a.id;mode='home';save();render();say(`找到${a.species}了！给它起个名字，欢迎它来玩。`);tone('find');animate('greeting',800)}
function animate(kind,duration){busy=true;$('#feed').disabled=$('#play').disabled=true;$('#pet-stage').className=kind;return new Promise(resolve=>setTimeout(()=>{$('#pet-stage').className='';busy=false;$('#feed').disabled=$('#play').disabled=false;resolve()},duration))}
async function care(kind){if(busy)return;mode='home';const before=MAPS.filter(unlocked).length,p=pet(),a=selected();if(kind==='feeding')p.full=Math.min(100,p.full+22);else{p.happy=Math.min(100,p.happy+24);p.full=Math.max(25,p.full-6)}p.bond=Math.min(6,p.bond+1);state.care++;render();$('#food').textContent=a.snack;save();tone(kind==='feeding'?'feed':'play');say(kind==='feeding'?`${displayName(a)}凑过来，吃起了${a.food}。`:`${displayName(a)}追着球跑，又跳了起来！`);await animate(kind,kind==='feeding'?1200:1400);if(MAPS.filter(unlocked).length>before){say(`${MAPS[before].name}开放了！点左边的地图，去找新朋友。`);tone('find')}else say(kind==='feeding'?`${displayName(a)}吃好了，${p.full===100?'肚子饱饱的，可以陪它玩一会儿。':'还想和你待一会儿。'}`:`${displayName(a)}玩得很高兴！也可以去地图里找其他动物。`)}
$('#feed').onclick=()=>care('feeding');$('#play').onclick=()=>care('playing');$('#pet-body').onclick=()=>{if(!busy){tone('play');say(`${displayName(selected())}跳起来，跟你打了个招呼。`);animate('greeting',800)}};
$('#home-mode').onclick=()=>{if(!busy){mode='home';render();say('选一只动物，喂它吃东西，或者陪它玩球。')}};
$('#explore-mode').onclick=()=>{if(!busy){mode='explore';render();say(`在${MAPS[state.map].name}找找看，谁藏起来了？`)}};
$('#name-form').onsubmit=e=>{e.preventDefault();if(busy)return;const name=$('#name-input').value.trim().slice(0,12);if(!name){say('先写一个名字吧。');$('#name-input').focus();return}pet().name=name;save();render();say(`好呀，以后就叫${name}！`);tone('find')};
$('#sound').onclick=()=>{state.sound=!state.sound;save();$('#sound').textContent=state.sound?'♪ 声音开':'♪ 声音关';$('#sound').setAttribute('aria-pressed',state.sound);tone('feed')};
$('#reset').onclick=()=>{if(busy)return;if(!resetPending){resetPending=true;$('#reset').textContent='确定重新开始';$('#cancel-reset').hidden=false;say('重新开始会清空这台设备上保存的动物和名字。想好了再点一次。');return}state=fresh();mode='home';resetPending=false;$('#reset').textContent='重新开始';$('#cancel-reset').hidden=true;save();render();say('从小猫开始，重新认识动物朋友吧。')};
$('#cancel-reset').onclick=()=>{resetPending=false;$('#reset').textContent='重新开始';$('#cancel-reset').hidden=true;say('好，继续和小动物玩。')};
render();if(Object.keys(state.pets).length>1||pet().name)say(`欢迎回来！${displayName(selected())}在等你。`);
