import {PARTS,DESIGN_TEMPLATES,newDesign,loadDesign,saveDesign,validateDesign,drawPart,drawCustomPuppet,invalidateDesign} from './custom-puppet.mjs';
import {fineArtReady,designArtSpec} from './fine-puppet.mjs';
const $=id=>document.getElementById(id),canvas=$('drawing'),g=canvas.getContext('2d'),preview=$('preview'),pg=preview.getContext('2d');
let design=loadDesign()||newDesign('wukong'),part='head',tool='ink',stroke=null,backup=null,history=[],action=null,dirty=false;
const LIBRARY_KEY='shadow-puppet-library-v1';let library=[];try{library=JSON.parse(localStorage.getItem(LIBRARY_KEY)||'[]').slice(0,12).map(validateDesign);}catch{}
const clone=x=>JSON.parse(JSON.stringify(x));const say=s=>$('status').textContent=s;
try{backup=JSON.parse(localStorage.getItem('shadow-puppet-previous-v1')||'null');}catch{}
function remember(){history.push(clone(design));if(history.length>40)history.shift();dirty=true;}
function fields(){for(const [id,key] of [['name','name'],['prop-name','propName'],['story','story'],['move','move'],['mood','music']])$(id).value=design[key];$('template').value=design.template;}
function render(){invalidateDesign(design);drawPart(g,design.parts[part],true);$('fill').value=design.parts[part].color;$('part-label').textContent=PARTS[part];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===part)));document.querySelectorAll('[data-template]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.template===design.template)));$('undo').disabled=!history.length;$('restore').disabled=!backup;}
function sync(){for(const [id,key] of [['name','name'],['prop-name','propName'],['story','story'],['move','move'],['mood','music']])design[key]=$(id).value;dirty=true;}
Object.entries(PARTS).forEach(([id,name])=>{const b=document.createElement('button');b.textContent=name;b.dataset.part=id;b.onclick=()=>{part=id;render();};$('parts').append(b);});
const tips={ink:'用鼠标或手指画花纹。',cut:'划过的地方会透光。别把关节周围挖空。',outline:'一笔围出新形状，松手封口；可撤回。',pivot:'点击纸片放关节点；拖到不同位置，看看转动有什么变化。'};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('tool-help').textContent=tips[tool];});
const at=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(256,(e.clientX-r.left)/r.width*256)),Math.max(0,Math.min(320,(e.clientY-r.top)/r.height*320))];};
canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();remember();canvas.setPointerCapture(e.pointerId);const p=at(e);stroke={tool,color:$('ink').value,width:Number($('width').value),points:[p]};if(tool==='pivot')design.parts[part].pivot=p;else if(tool!=='outline')design.parts[part].strokes.push(stroke);render();};
canvas.onpointermove=e=>{if(!stroke)return;const p=at(e);if(tool==='pivot'){design.parts[part].pivot=p;render();return;}if(stroke.points.length<1200&&Math.hypot(p[0]-stroke.points.at(-1)[0],p[1]-stroke.points.at(-1)[1])>1.5)stroke.points.push(p);render();if(tool==='outline'){g.beginPath();stroke.points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.strokeStyle='#3e705a';g.lineWidth=2;g.stroke();}};
canvas.onpointerup=()=>{if(!stroke)return;if(tool==='outline'&&stroke.points.length>=3){design.parts[part].outline=clone(stroke.points);delete design.parts[part].art;delete design.parts[part].artPart;}stroke=null;render();};canvas.onpointercancel=()=>{if(stroke){design=history.pop()||design;stroke=null;render();}};
$('undo').onclick=()=>{if(history.length){design=history.pop();dirty=true;fields();render();}};
$('clear-detail').onclick=()=>{remember();design.parts[part].strokes=[];render();say('这片的花纹已清空，轮廓和关节还在。可撤回。');};
$('fill').onchange=()=>{remember();design.parts[part].color=$('fill').value;design.parts[part].tint=true;render();};
for(const id of ['name','prop-name','story','move','mood'])$(id).oninput=sync;
function stash(){backup=clone(design);try{localStorage.setItem('shadow-puppet-previous-v1',JSON.stringify(backup));}catch{} }
function chooseTemplate(id){stash();remember();design=newDesign(id);fields();render();say('已换人物底稿。可以加花纹、镂空或改颜色，上一稿已保留。');}
$('new-template').onclick=()=>chooseTemplate($('template').value);
const templateCanvases=[];for(const template of DESIGN_TEMPLATES){$('template').add(new Option(template.name,template.id));const button=document.createElement('button'),thumb=document.createElement('canvas'),name=document.createElement('span');button.type='button';button.dataset.template=template.id;button.setAttribute('aria-label','用'+template.name+'作为底稿');thumb.width=240;thumb.height=280;name.textContent=template.name;button.append(thumb,name);button.onclick=()=>chooseTemplate(template.id);$('template-gallery').append(button);templateCanvases.push({canvas:thumb,design:newDesign(template.id)});}
fineArtReady.then(()=>{for(const item of templateCanvases){const cg=item.canvas.getContext('2d');cg.save();cg.translate(120,140);cg.scale(.82,.82);cg.translate(-550,-320);drawCustomPuppet(cg,{x:.5,y:.42,slot:0,thumb:.5,fingers:[.5,.5,.5,.5],props:true,rig:'none',hideLabel:true},1100,650,item.design);cg.restore();}render();});
function refreshLibrary(){$('library').replaceChildren(new Option('选择我存过的人物',''),...library.map((entry,i)=>new Option(entry.name,String(i))));}
$('library-save').onclick=()=>{try{sync();const entry=validateDesign(design),next=library.filter(item=>item.name!==entry.name);if(next.length>=12)throw Error('角色库最多存 12 个名字，先导出一份再继续。');next.push(entry);localStorage.setItem(LIBRARY_KEY,JSON.stringify(next));library=next;refreshLibrary();say('已存入角色库。同名作品会更新；不同名字分别保留。');}catch(e){say('角色库未更新：'+e.message);}};
$('library').onchange=()=>{if($('library').value==='')return;const next=library[Number($('library').value)];if(!next)return;stash();remember();design=validateDesign(next);fields();render();say('已取出“'+design.name+'”，可以继续修改或送上舞台。');};refreshLibrary();
$('restore').onclick=()=>{try{const previous=validateDesign(backup);stash();remember();design=previous;fields();render();say('已找回上一稿。');}catch(e){say(e.message);}};
function save(){try{sync();design=saveDesign(design);dirty=false;render();say('已保存到这台浏览器。导出作品可以带到另一台电脑。');return true;}catch(e){say('没有保存：'+e.message);return false;}}
$('save').onclick=save;$('perform').onclick=()=>{if(save())location.href='app/index.html?character=student';};
$('export').onclick=()=>{try{sync();const valid=validateDesign(design),url=URL.createObjectURL(new Blob([JSON.stringify(valid,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='my-shadow-puppet.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('作品已导出。记得给同伴讲讲设计。');}catch(e){say(e.message);}};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>1500000)throw Error('文件过大，请使用工坊导出的作品。');const next=validateDesign(JSON.parse(await file.text()));stash();remember();design=next;fields();render();say('作品已导入。检查后可保存或送上舞台。');}catch(e){say('没有导入：'+e.message);}finally{$('import').value='';}};
const bodyPrintAnchors=()=>{const spec=designArtSpec(design.template);return spec?Object.values(spec.anchors):[[128,85],[78,111],[178,111],[103,238],[153,238]];};
$('jump').onclick=()=>{action={name:'jump',started:performance.now()};};$('use-prop').onclick=()=>{action={name:'prop',started:performance.now()};};
function frame(now){pg.clearRect(0,0,700,560);pg.save();pg.translate(350,255);pg.scale(1.8,1.8);pg.translate(-550,-320);const value=i=>Number(document.querySelector('[data-finger="'+i+'"]').value);if(action&&now-action.started>1000)action=null;drawCustomPuppet(pg,{x:.5,y:.42,slot:0,thumb:value(0),fingers:[1,2,3,4].map(value),props:true,rig:$('threads').checked?'strings':'none',hideLabel:true,action:action?{name:action.name,progress:Math.min(1,(now-action.started)/1000)}:null},1100,650,design);pg.restore();requestAnimationFrame(frame);}
function makePrint(){sync();$('print-brief').textContent=design.name+' · 道具：'+design.propName+' · '+design.story+' · 拿手动作：'+design.move;$('print-parts').replaceChildren();for(const [id,label] of Object.entries(PARTS)){const fig=document.createElement('figure'),c=document.createElement('canvas'),caption=document.createElement('figcaption');c.width=256;c.height=320;const cg=c.getContext('2d');drawPart(cg,design.parts[id],id!=='body');if(id==='body')for(const p of bodyPrintAnchors()){cg.beginPath();cg.arc(...p,5,0,Math.PI*2);cg.fillStyle='#fff';cg.fill();cg.strokeStyle='#222';cg.stroke();}caption.textContent=label+(id==='prop'?' · '+design.propName:'');fig.append(c,caption);$('print-parts').append(fig);}}
$('print').onclick=()=>{makePrint();window.print();};window.addEventListener('beforeprint',makePrint);
window.addEventListener('beforeunload',()=>{if(dirty){try{saveDesign(design);}catch{}}});
fields();render();requestAnimationFrame(frame);
if(new URLSearchParams(location.search).has('test'))window.__designer={snapshot:()=>clone(design),print:makePrint};
