import {STATIC_HOST} from './runtime-config.mjs';
import {DramaRecorder,encodePCM,waveBlob} from './drama-audio.mjs';
import {DramaTTS} from './drama-tts.mjs';
import {summarize,reportData,RUBRIC,wordStates,AGE_THRESHOLDS} from './drama-state.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const score=n=>Number.isFinite(n)?n+' / 100':'—';
export class DramaController{
 constructor({mount,prepareStage,selectRole,quiet}){
  this.prepareStage=prepareStage;this.selectRole=selectRole;this.quiet=quiet;this.recorder=new DramaRecorder();this.attempts=new Map();this.audioURL=null;this.epoch=0;this.sequence=0;this.mode='rehearsal';this.index=0;this.pending=new Set();this.controllers=new Set();this.busy=false;this.recording=false;
  mount.innerHTML=`<details id="drama-panel" class="drama-panel"><summary>英语小剧场 <span>选一出戏，边说边演</span></summary><div class="drama-body">
   <div class="drama-setup"><label>选剧场<select id="drama-play"></select></label><label>练谁的台词<select id="drama-role"><option value="all">所有角色</option></select></label><button id="drama-set">布置这出戏</button><a href="../english-drama.html">看教案 ↗</a></div>
   <p id="drama-intro"></p><p class="drama-note">麦克风由你开启。一次一位同学说话；网页录音留在本次浏览器会话内，本机版本可另启用发音评估。录音时配乐暂停。</p>
   <div class="drama-line-tools"><span id="drama-line-number"></span><label>跳到一句<select id="drama-line-select" aria-label="选择台词"></select></label><label><input type="checkbox" id="drama-show-zh" checked>显示中文</label></div>
   <div class="drama-script"><span id="drama-speaker"></span><div class="drama-prompter" id="drama-prompter" tabindex="0" aria-label="三行提词器，上下方向键换句"><p id="drama-before" class="drama-neighbor" lang="en"></p><p id="drama-line" lang="en"></p><p id="drama-after" class="drama-neighbor" lang="en"></p></div><p id="drama-zh"></p><p id="drama-cue"></p></div>
   <p class="drama-legend">灰色看前后句，黑色读当前句。读到并达到练习线的词变蓝，其他词保持原样。可用上下键或下方按钮换句。</p>
   <div id="drama-words" class="drama-words"></div>
   <div class="drama-buttons"><button id="drama-listen">听这一句</button><button id="drama-record" class="primary">录这一句</button><button id="drama-stop" disabled>读完了，停止</button><button id="drama-cancel" disabled>取消录音</button><button id="drama-replay" disabled>回听录音</button><button id="drama-prev">上一句</button><button id="drama-next">下一句</button></div>
   <div class="drama-meter"><meter id="drama-level" min="0" max="1" value="0" aria-label="麦克风音量"></meter><span id="drama-seconds">每句最多 25 秒</span></div>
   <p id="drama-status" role="status">先选一句试说。听示范后，再开麦克风。</p><p id="drama-engine" class="drama-note"></p><div id="drama-tts-mount"></div>
   <section id="drama-feedback" class="drama-feedback" aria-label="本句反馈"><p>录过后，先回听，再看反馈。</p></section>
   <details class="drama-teacher"><summary>老师备课：选词与跟读难度</summary><label>练习档<select id="drama-difficulty"><option value="age">按本剧年龄建议</option><option value="50">轻松试试 · 50</option><option value="60">多练一句 · 60</option><option value="70">再挑战 · 70</option><option value="custom">老师调整</option></select></label><label>蓝字点亮门槛 <output id="drama-threshold-value">50 分</output><input id="drama-threshold" type="range" min="30" max="90" step="5" value="50"></label><p id="drama-threshold-note">只调整鼓励提示，不改变评分。年龄建议是课堂起点，不是能力标准。</p><p>用空格或逗号分隔英文词。只改变本剧场的提示，不改变识别结果。</p><label>本组要练的词<input id="drama-hard-words" maxlength="350"></label><button id="drama-save-words">保存选词</button><button id="drama-reset-words">恢复备课选词</button></details>
   <div class="drama-performance"><div><h3>最后演一遍</h3><p id="drama-take">当前是排练。正式演出会新开一份记录，按剧本顺序逐句录音；换人时由同伴点下一句。台词和操偶一起完成。</p></div><div class="drama-buttons"><button id="drama-start-show">开始正式演出</button><button id="drama-finish-show" disabled>结束，看本场记录</button><button id="drama-export">导出本轮记录</button></div></div>
   <div id="drama-report" class="drama-report"></div>
   <div class="drama-rubric">${RUBRIC.map(([id,label])=>`<label>${label}<select id="drama-rubric-${id}"><option value="">老师暂未记录</option><option value="1">1 · 在帮助下试演</option><option value="2">2 · 有几处需要提醒</option><option value="3">3 · 能独立完成</option><option value="4">4 · 能根据观众反应调整</option></select></label>`).join('')}</div><label class="drama-notes">老师的一条建议<textarea id="drama-teacher-notes" rows="2" maxlength="1000" placeholder="指向一句台词或一个动作，下次再试。"></textarea></label>
   <p class="drama-note">台词匹配看读到了哪些词；发音参考分来自音素识别，尚未用儿童语音校准。弱读、连读和口音可能被误判。两种分数分开看，由老师结合回听确认；未录到的句子不算零分，也不算通过。</p>
  </div></details>`;
  $('drama-play').onchange=()=>this.choose($('drama-play').value);$('drama-role').onchange=()=>{this.filterLines();this.go(this.visible[0]);};$('drama-set').onclick=()=>{this.prepareStage(this.play);this.message('布景和前两位演员已就位。摄像头模式下，角色仍按固定手部编号控制。');};
  $('drama-difficulty').onchange=()=>{const choice=$('drama-difficulty').value;this.threshold=choice==='age'?AGE_THRESHOLDS[this.play.age]:choice==='custom'?Number($('drama-threshold').value):Number(choice);this.updateThreshold();};$('drama-threshold').oninput=()=>{$('drama-difficulty').value='custom';this.threshold=Number($('drama-threshold').value);this.updateThreshold();};
  $('drama-prompter').onkeydown=event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();this.step(event.key==='ArrowDown'?1:-1);}};
  $('drama-prompter').addEventListener('wheel',event=>{if(Math.abs(event.deltaY)>20&&!this.recording&&!this.busy){event.preventDefault();if(performance.now()-(this.lastScroll||0)>450){this.lastScroll=performance.now();this.step(event.deltaY>0?1:-1);}}},{passive:false});
  $('drama-line-select').onchange=()=>this.go(Number($('drama-line-select').value));$('drama-prev').onclick=()=>this.step(-1);$('drama-next').onclick=()=>this.step(1);$('drama-show-zh').onchange=()=>{$('drama-zh').hidden=!$('drama-show-zh').checked;};
  $('drama-listen').onclick=()=>this.listen();$('drama-record').onclick=()=>this.record();$('drama-stop').onclick=()=>this.stop();$('drama-cancel').onclick=()=>this.cancelRecording();$('drama-replay').onclick=()=>{this.quiet();this.cancelPlayback();this.player=new Audio(this.audioURL);this.player.play().catch(()=>this.message('回听没有开始，请再点一次。'));};
  $('drama-start-show').onclick=()=>this.startShow();$('drama-finish-show').onclick=()=>this.finishShow();$('drama-export').onclick=()=>this.export();
  $('drama-save-words').onclick=()=>{this.hardWords=$('drama-hard-words').value.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[];try{localStorage.setItem('shadow-drama-words-'+this.play.id,JSON.stringify(this.hardWords));}catch{}this.renderLine();this.message('选词已保存，台词中的这些词会加下划线。');};
  $('drama-reset-words').onclick=()=>{this.hardWords=this.play.words.map(w=>w[0]);$('drama-hard-words').value=this.hardWords.join(', ');try{localStorage.setItem('shadow-drama-words-'+this.play.id,JSON.stringify(this.hardWords));}catch{}this.renderLine();};
  $('drama-panel').addEventListener('toggle',()=>{if(!$('drama-panel').open){this.cancelRecording();this.cancelPlayback();}});
  const body=mount.querySelector('.drama-body'),script=mount.querySelector('.drama-script'),legend=mount.querySelector('.drama-legend'),buttons=mount.querySelector('.drama-buttons');body.prepend(script);script.after(legend);legend.after(buttons);buttons.after($('drama-status'));$('drama-status').after(mount.querySelector('.drama-meter'));
  this.tts=new DramaTTS({mount:$('drama-tts-mount'),script:()=>this.play,line:()=>this.index,canPlay:()=>!this.recording&&!this.busy,quiet:this.quiet,status:text=>this.message(text)});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)this.suspend();});window.addEventListener('pagehide',()=>this.suspend());
  this.ready=this.load();
 }
 message(text){$('drama-status').textContent=text;}
 async load(){try{const response=await fetch('../teaching/stage-plays.json');if(!response.ok)throw Error('台词资料未能载入。');const data=await response.json();this.plays=data.plays;for(const p of this.plays)$('drama-play').add(new Option(`${p.title} · ${p.age} 岁`,p.id));const query=new URLSearchParams(location.search).get('drama');this.choose(this.plays.find(p=>p.id===query)?.id||this.plays.find(p=>p.age===query)?.id||'moon-gift');if(query)$('drama-panel').open=true;
   if(STATIC_HOST){$('drama-engine').textContent='网页支持录音与回听。自动台词核对和发音参考请在本机课程中启用。';return;}const r=await fetch('/api/speech/status');const status=await r.json();$('drama-engine').textContent=status.error?status.error:((status.asr?'本机 SenseVoice 已找到':'本机 SenseVoice 未准备好')+' · '+(status.phones?'音素练习模型已找到':'音素模型尚未准备好')+'。首次评估需要载入模型，请稍等。');
  }catch(error){this.message(error.message);}}
 choose(id){
  this.suspend();this.epoch++;this.pending.clear();this.attempts.clear();this.mode='rehearsal';this.play=this.plays.find(p=>p.id===id)||this.plays[0];$('drama-play').value=this.play.id;$('drama-intro').textContent=this.play.summary;
  $('drama-role').replaceChildren(new Option('所有角色','all'),...this.play.roles.map(role=>new Option(role,role)));this.hardWords=this.play.words.map(w=>w[0]);try{const saved=JSON.parse(localStorage.getItem('shadow-drama-words-'+this.play.id));if(Array.isArray(saved)&&saved.every(w=>typeof w==='string'))this.hardWords=saved;}catch{}
  $('drama-hard-words').value=this.hardWords.join(', ');for(const [id] of RUBRIC)$('drama-rubric-'+id).value='';$('drama-teacher-notes').value='';this.filterLines();this.go(0);this.updateReport();this.updateButtons();this.message('已选“'+this.play.title+'”。点“布置这出戏”，再分角色排练。');
  this.threshold=AGE_THRESHOLDS[this.play.age];$('drama-difficulty').value='age';this.updateThreshold();this.tts?.updatePreset();$('drama-take').textContent='当前是排练。正式演出会新开一份记录，按剧本顺序逐句录音；换人时由同伴点下一句。台词和操偶一起完成。';
 }
 filterLines(){this.visible=this.play.lines.flatMap((row,i)=>$('drama-role').value==='all'||row[0]===$('drama-role').value?[i]:[]);$('drama-line-select').replaceChildren(...this.visible.map(i=>new Option(`${i+1}. ${this.play.lines[i][0]} · ${this.play.lines[i][1]}`,String(i))));}
 go(index){if(this.recording||this.busy)return;const direction=index>=this.index?1:-1;this.cancelPlayback();this.index=index;this.clearAudio();this.renderLine();this.updateButtons();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('drama-prompter').animate([{transform:`translateY(${direction*12}px)`,opacity:.7},{transform:'translateY(0)',opacity:1}],{duration:220,easing:'ease-out'});}
 step(delta){const at=this.visible.indexOf(this.index),next=this.visible[at+delta];if(next!=null)this.go(next);}
 renderLine(){const [role,en,zh,cue]=this.play.lines[this.index];$('drama-line-select').value=String(this.index);$('drama-line-number').textContent=`第 ${this.index+1} / ${this.play.lines.length} 句`;$('drama-speaker').textContent=role;$('drama-line').innerHTML=en.split(/([A-Za-z]+(?:'[A-Za-z]+)?)/).map(part=>this.hardWords.includes(part.toLowerCase())?`<mark>${esc(part)}</mark>`:esc(part)).join('');$('drama-zh').textContent=zh;$('drama-zh').hidden=!$('drama-show-zh').checked;$('drama-cue').textContent='操偶提示 · '+cue;
  const rowWords=en.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[];$('drama-words').replaceChildren(...this.hardWords.filter(w=>rowWords.includes(w)).map(word=>{const note=this.play.words.find(w=>w[0]===word),el=document.createElement('span');el.textContent=word+(note?' · '+note[1]:' · 试着连在句子里读');el.title=note?.[2]||'教师选词';return el;}));this.paintWords(this.attempts.get(this.index)?.result,true);
  const at=this.visible.indexOf(this.index),before=this.visible[at-1],after=this.visible[at+1];$('drama-before').textContent=before==null?'准备开场':this.play.lines[before][1];$('drama-after').textContent=after==null?'这一幕演完了':this.play.lines[after][1];const roleIndex=this.play.roles.filter(r=>r!=='旁白').indexOf(role);if(roleIndex>=0)this.selectRole(roleIndex);this.feedback();
 }
 cancelPlayback(){this.tts?.cancel();window.speechSynthesis?.cancel();if(this.player){this.player.pause();this.player.src='';this.player=null;}}
 paintWords(result,final=false){const text=this.play.lines[this.index][1],states=wordStates(text,result,final,this.threshold??AGE_THRESHOLDS[this.play.age]);let index=0;$('drama-line').innerHTML=text.split(/([A-Za-z]+(?:'[A-Za-z]+)?)/).map(part=>{if(!/^[A-Za-z]+(?:'[A-Za-z]+)?$/.test(part))return esc(part);const item=states[index++],hint=item.label;return `<span class="drama-word word-${item.state}${this.hardWords.includes(part.toLowerCase())?' hard-word':''}" data-state="${item.state}" title="${esc(hint)}" aria-label="${esc(part+'，'+hint)}">${esc(part)}</span>`;}).join('');}
 updateThreshold(){$('drama-threshold').value=String(this.threshold);$('drama-threshold-value').textContent=this.threshold+' 分';this.paintWords(this.recording?this.liveResult:this.attempts.get(this.index)?.result,true);}
 async liveTranscript(){
  if(STATIC_HOST||!this.recording||this.liveBusy)return;const samples=this.recorder.snapshot();if(!samples||samples.length<16000)return;this.liveBusy=true;const epoch=this.epoch,index=this.index,token=this.recordToken,controller=new AbortController();this.liveController=controller;const timeout=setTimeout(()=>controller.abort(),10000);
  try{const response=await fetch('/api/speech/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pcm:encodePCM(samples).base64,sampleRate:16000,reference:this.play.lines[index][1]}),signal:controller.signal});if(!response.ok)return;const result=await response.json();if(epoch===this.epoch&&index===this.index&&token===this.recordToken&&this.recording){this.paintWords(result,true);this.liveResult=result;}}
  catch{}finally{clearTimeout(timeout);if(this.liveController===controller){this.liveController=null;this.liveBusy=false;}}
 }
 listen(){if(this.recording||this.busy)return;this.cancelPlayback();return this.tts.listen();}
 async record(){
  if(this.busy||this.recording)return;if(this.pending.size>=2){this.message('还有两句正在评估，稍等结果回来后再录。');return;}this.cancelPlayback();this.quiet();this.clearAudio();this.busy=true;this.updateButtons();const epoch=this.epoch,seq=++this.sequence;this.recordToken=seq;this.message(STATIC_HOST?'正在请求麦克风，读完可以回听。':'正在准备本机语音识别，随后请求麦克风…');this.paintWords(null);this.liveResult=null;
  try{if(!STATIC_HOST&&!this.prepared){const response=await fetch('/api/speech/prepare',{method:'POST'});const result=await response.json();if(!response.ok)throw Error(result.error||'本机语音模型未能载入。');this.prepared=true;}if(epoch!==this.epoch||seq!==this.sequence)return;const ok=await this.recorder.start((level,seconds)=>{$('drama-level').value=level;$('drama-seconds').textContent=seconds.toFixed(1)+' / 25 秒';if(seconds>=24.7&&this.recording)this.stop();});if(!ok||epoch!==this.epoch||seq!==this.sequence)return;this.busy=false;this.recording=true;this.message('正在录音 · '+this.play.lines[this.index][0]+'。慢慢读，读完后点停止。');this.limit=setTimeout(()=>this.stop(),25000);this.liveTimer=setInterval(()=>this.liveTranscript(),1600);this.updateButtons();}
  catch(error){if(epoch===this.epoch&&seq===this.sequence){this.busy=false;this.message(error.name==='NotAllowedError'?'麦克风没有获准开启。可在浏览器地址栏设置，或继续听示范、由老师反馈。':'麦克风未能开启：'+error.message);this.updateButtons();}}
 }
 async stop(){
  if(!this.recording)return;clearTimeout(this.limit);clearInterval(this.liveTimer);this.liveController?.abort();this.recording=false;this.busy=true;this.updateButtons();const epoch=this.epoch,index=this.index,seq=this.sequence;
  try{const samples=await this.recorder.stop();if(epoch!==this.epoch||seq!==this.sequence)return;const pcm=encodePCM(samples);this.audioURL=URL.createObjectURL(waveBlob(pcm.bytes));this.busy=false;if(STATIC_HOST){this.attempts.set(index,{id:++this.sequence,state:'unscored',result:{quality:{usable:false,message:'这句已录下，可以回听。请同伴或老师给一条建议。'},content:null,pronunciation:null}});this.feedback();this.updateReport();this.message('录音结束，可以回听；本页不产生自动评分。');}else this.assess(index,pcm.base64,epoch);this.updateButtons();}
  catch(error){if(epoch===this.epoch&&seq===this.sequence){this.busy=false;this.message(error.message);this.updateButtons();}}
 }
 async assess(index,pcm,epoch){
  const id=++this.sequence,attempt={id,state:'pending'};this.attempts.set(index,attempt);this.pending.add(id);this.updateReport();this.feedback();this.message('录音结束，本机正在评估。可以继续操偶，或换到下一句。');const controller=new AbortController();this.controllers.add(controller);const timeout=setTimeout(()=>controller.abort(),95000);
  try{const response=await fetch('/api/speech/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pcm,sampleRate:16000,reference:this.play.lines[index][1]}),signal:controller.signal});const result=await response.json();if(!response.ok||result.error)throw Error(result.error||'评估没有完成。');if(epoch!==this.epoch||this.attempts.get(index)?.id!==id)return;Object.assign(attempt,{state:result.quality?.usable?'done':'unscored',result});if(index===this.index&&!this.recording)this.message(result.quality?.message||'本句反馈已回来。先回听，再挑一个词重练。');}
  catch(error){if(epoch===this.epoch&&this.attempts.get(index)?.id===id){Object.assign(attempt,{state:'error',error:error.name==='AbortError'?'评估已取消或超时，可重录。':error.message});if(index===this.index&&!this.recording)this.message(attempt.error);}}
  finally{clearTimeout(timeout);this.controllers.delete(controller);this.pending.delete(id);if(epoch===this.epoch){if(!this.recording&&!this.busy)this.paintWords(this.attempts.get(this.index)?.result,true);this.feedback();this.updateReport();this.updateButtons();}}
 }
 cancelRecording(){clearTimeout(this.limit);clearInterval(this.liveTimer);this.liveController?.abort();this.sequence++;this.recorder.cancel();const active=this.recording||this.busy;this.recording=false;this.busy=false;$('drama-level').value=0;if(active)this.message('录音已取消，没有提交这一段。');this.updateButtons();}
 clearAudio(){this.cancelPlayback();if(this.audioURL){URL.revokeObjectURL(this.audioURL);this.audioURL=null;}$('drama-replay').disabled=true;}
 suspend(){this.cancelRecording();this.clearAudio();for(const controller of this.controllers)controller.abort();this.controllers.clear();}
 feedback(){const item=this.attempts.get(this.index),out=$('drama-feedback');if(!item){out.innerHTML='<p>这一句还没录。可以先听，再试着配上动作。</p>';return;}if(item.state==='pending'){out.innerHTML='<p>本句正在本机评估…</p>';return;}if(item.error){out.textContent=item.error;return;}const r=item.result;if(!r.quality?.usable){out.textContent=r.quality?.message||'本句没有评分，请重录。';return;}out.innerHTML=`<div class="drama-score-pair"><div><span>台词匹配</span><b>${score(r.content?.score)}</b><small>识别到的词与剧本核对</small></div><div><span>发音参考 · 试验</span><b>${score(r.pronunciation?.score)}</b><small>音素序列相似度，需回听确认</small></div></div><p>听到的是：<span lang="en" data-i18n-preserve>${esc(r.transcript)}</span></p><div class="drama-word-results">${(r.content?.words||[]).map(w=>`<span class="${w.kind}">${esc(w.expected||w.heard)}${w.kind==='missing'?' · 未识别到':w.kind==='replace'?' → '+esc(w.heard):w.kind==='extra'?' · 多识别到':''}</span>`).join('')}</div>${r.pronunciation?.score==null?`<p>${esc(r.pronunciation?.reason||'本句暂无发音参考分。')}</p>`:`<p>可以回听这些词：${(r.pronunciation.words||[]).filter(w=>w.score<75).map(w=>esc(w.word)).join('、')||'本句暂未标出。仍请听一遍自己的录音。'}</p><details><summary>查看音素记录（供老师参考）</summary><p>音素识别也会出错；下列分数不等于单词发音正确率。</p>${(r.pronunciation.words||[]).map(w=>`<p lang="en">${esc(w.word)} · ${w.score}/100 · 参考 /${esc(w.expected)}/ · 识别 /${esc(w.heard)}/</p>`).join('')}</details>`}`;}
 updateButtons(){if(!this.play)return;const locked=this.busy||this.recording;$('music-toggle').disabled=locked;$('drama-record').disabled=locked||this.pending.size>=2;$('drama-stop').disabled=!this.recording;$('drama-cancel').disabled=!locked;$('drama-replay').disabled=locked||!this.audioURL;$('drama-listen').disabled=locked;for(const id of ['drama-play','drama-role','drama-line-select','drama-set','drama-start-show'])$(id).disabled=locked;const at=this.visible.indexOf(this.index);$('drama-prev').disabled=locked||at<=0;$('drama-next').disabled=locked||at>=this.visible.length-1;$('drama-finish-show').disabled=locked||this.mode!=='performance';$('drama-role').disabled=locked||this.mode==='performance';}
 startShow(){if(this.pending.size){this.message('等本轮评估回来，导出后再开新一场。');return;}this.cancelRecording();this.clearAudio();this.epoch++;this.mode='performance';this.attempts.clear();$('drama-role').value='all';this.filterLines();this.go(0);for(const [id] of RUBRIC)$('drama-rubric-'+id).value='';$('drama-teacher-notes').value='';$('drama-take').textContent=STATIC_HOST?'正式演出中 · 每句点录音，说完停止，再换下一句。先演完，再请老师给建议。':'正式演出中 · 每句点录音，说完停止，再换下一句。机器在后台处理，操偶可以继续。';this.updateReport();this.updateButtons();this.message('新一场已开始。旁白先准备；每句由台词旁标出的角色说。');}
 finishShow(){this.mode='finished';$('drama-take').textContent='这场演出结束了。先看录了几句，再回听需要帮助的词，请老师写一条建议。';this.updateReport();this.updateButtons();$('drama-report').scrollIntoView({behavior:'smooth',block:'nearest'});this.message(this.pending.size?'演出已结束，剩余录音评估完成后会补入记录。':'本场记录已汇总。老师的观察与机器反馈分别记录。');}
 updateReport(){const report=summarize(this.play,this.attempts);$('drama-report').innerHTML=`<p><b>${esc(this.play.title)}</b> · 已录 ${report.recorded} / ${report.expected} 句${report.pending?' · '+report.pending+' 句处理中':''} · ${this.mode==='rehearsal'?'排练记录':'本场演出记录'}</p><div class="drama-table-scroll"><table><thead><tr><th>角色</th><th>已录 / 应录</th><th>台词匹配</th><th>发音参考 · 试验</th></tr></thead><tbody>${report.roles.map(r=>`<tr><td>${esc(r.role)}</td><td>${r.recorded} / ${r.expected}</td><td>${score(r.content)}<small>${r.contentCount} 句可评</small></td><td>${score(r.pronunciation)}<small>${r.phoneCount} 句可评</small></td></tr>`).join('')}</tbody></table></div><p class="drama-note">每句用本轮最后一次录音；仅对可评的句子求平均。录音失败或漏录不会补零，覆盖情况单独列出。</p>`;}
 export(){const rubric=Object.fromEntries(RUBRIC.map(([id,label])=>[id,{label,score:$('drama-rubric-'+id).value?Number($('drama-rubric-'+id).value):null}])),report=reportData(this.play,this.attempts,this.mode,rubric,$('drama-teacher-notes').value);report.feedbackPolicy={age:this.play.age,blueThreshold:this.threshold,changesRawScores:false};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='shadow-drama-'+this.play.id+'-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.message('已导出文字记录，不含录音。');}
}
