export const CUES={hero:{name:'小将出场',bpm:96,file:'hero-shadow-r3.wav'},play:{name:'灯下游戏',bpm:104,file:'play-chinese-r2.wav'},moon:{name:'月下散步',bpm:72,file:'moon-shadow-r5.wav'},festival:{name:'灯会碰面',bpm:104,file:'festival-shadow-r3.wav'}};
const families={wukong:'hero',nezha:'hero',bajie:'hero',erlang:'hero',mulan:'hero',bluey:'play',doraemon:'play',kuromi:'play',kanao:'moon',yutu:'moon',change:'moon'};
export function chooseCue(characters){const groups=new Set(characters.map(c=>typeof c==='string'?families[c]||'play':c.music||families[c.character]||'play'));return groups.size>1?'festival':groups.size?[...groups][0]:null;}
export class CuePolicy{
 constructor(){this.current=null;this.candidate=null;this.since=0;this.changedAt=-Infinity;}
 update(characters,now,manual='auto',force=false){const wanted=manual==='auto'?chooseCue(characters):(CUES[manual]?manual:null);if(wanted!==this.candidate){this.candidate=wanted;this.since=now;}if(wanted===this.current)return {cue:this.current,changed:false};if(force||(now-this.since>=1800&&(wanted===null||now-this.changedAt>=10000))){this.current=wanted;this.changedAt=now;return {cue:wanted,changed:true};}return {cue:this.current,changed:false};}
}
export class MusicPlayer{
 constructor(){this.context=null;this.master=null;this.volume=.25;this.enabled=false;this.current=null;this.sources=new Set();this.buffers=new Map();this.serial=0;}
 async enable(){if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=this.volume;this.master.connect(this.context.destination);}this.enabled=true;const serial=++this.serial;await this.context.resume();return this.enabled&&this.serial===serial;}
 setVolume(v){this.volume=Math.max(0,Math.min(1,v));if(this.master)this.master.gain.setTargetAtTime(this.volume,this.context.currentTime,.08);}
 async buffer(id){if(!this.buffers.has(id))this.buffers.set(id,(async()=>{const r=await fetch(new URL('../assets/music/'+CUES[id].file,import.meta.url));if(!r.ok)throw Error('伴奏文件未能载入');return this.context.decodeAudioData(await r.arrayBuffer());})().catch(e=>{this.buffers.delete(id);throw e;}));return this.buffers.get(id);}
 async change(id){if(!this.enabled)return false;const serial=++this.serial;if(!id){this.fadeOut();this.current=null;return true;}const buffer=await this.buffer(id);if(!this.enabled||serial!==this.serial)return false;
  const ctx=this.context,now=ctx.currentTime;this.fadeOut();const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;source.connect(gain);gain.connect(this.master);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(1,now+1.6);const item={source,gain};this.sources.add(item);source.onended=()=>{source.disconnect();gain.disconnect();this.sources.delete(item);};source.start();this.current=id;return true;
 }
 fadeOut(){if(!this.context)return;const now=this.context.currentTime;for(const item of this.sources){if(item.stopping)continue;item.stopping=true;const param=item.gain.gain;if(param.cancelAndHoldAtTime)param.cancelAndHoldAtTime(now);else{const v=param.value;param.cancelScheduledValues(now);param.setValueAtTime(v,now);}param.linearRampToValueAtTime(0,now+1.6);item.source.stop(now+1.7);}}
 stop(immediate=false){this.enabled=false;this.serial++;this.current=null;if(immediate){for(const item of this.sources){try{item.source.stop();}catch{}}this.context?.suspend();}else this.fadeOut();}
}
export class MusicController{
 constructor(){this.player=new MusicPlayer();this.policy=new CuePolicy();this.characters=[];this.manual='auto';this.force=false;this.userPaused=false;this.starting=false;this.$=id=>document.getElementById(id);this.message='点一下舞台，伴奏会跟着人物播放。';this.$('music-toggle').onclick=()=>this.toggle();this.stageToggle=document.createElement('button');this.stageToggle.id='stage-music';this.stageToggle.type='button';this.stageToggle.onclick=()=>this.toggle();this.$('fullscreen').before(this.stageToggle);this.$('music-choice').onchange=()=>{this.manual=this.$('music-choice').value;this.force=true;};this.$('music-volume').oninput=()=>{const v=Number(this.$('music-volume').value);this.player.setVolume(v/100);this.$('music-level').textContent=v+'%';};document.addEventListener('pointerdown',e=>{if(!this.userPaused&&!this.player.enabled&&e.target.closest?.('#stage,#stage-camera,#camera,#fullscreen,#chinese-prev,#chinese-next,#chinese-set,#cast-gallery button'))this.start();},{capture:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.player.stop(true);this.message='页面已隐藏，音乐暂停。回来后点一下舞台可继续。';this.refresh();}});window.addEventListener('beforeunload',()=>this.player.stop(true));this.refresh();}
 async start(){if(this.starting||this.player.enabled)return;this.starting=true;try{this.message='正在载入伴奏…';this.refresh();const enabled=await this.player.enable();if(!enabled)return;const {cue}=this.policy.update(this.characters,performance.now(),this.manual,true);await this.player.change(cue);if(this.player.enabled)this.message=cue?'国乐配乐 · 可随时调低音量':'等待角色上场。';}catch(e){this.player.stop();this.message='没有播放：'+e.message;}finally{this.starting=false;this.refresh();}}
 async toggle(){if(this.player.enabled){this.userPaused=true;this.player.stop();this.message='音乐已暂停。';this.refresh();return;}this.userPaused=false;await this.start();}
 observe(puppets,studentMusic='play'){this.characters=puppets.filter(p=>p.state!=='dormant'&&p.state!=='candidate').map(p=>({character:p.character,music:p.character==='student'?studentMusic:undefined}));const result=this.policy.update(this.characters,performance.now(),this.manual,this.force);this.force=false;if(result.changed&&this.player.enabled){this.player.change(result.cue).then(ok=>{if(ok){this.message=result.cue?'国乐配乐 · 换曲时缓慢淡入淡出':'等待角色上场。';this.refresh();}}).catch(e=>{this.player.stop();this.message='没有播放：'+e.message;this.refresh();});}this.refresh();}
 refresh(){const cue=this.policy.current,name=cue?CUES[cue].name:'等待角色';const text=name+' · '+(this.manual==='auto'?'跟随上场人物':'手动选曲')+' · '+this.message;if(this.lastText!==text){this.$('music-status').textContent=text;this.lastText=text;}if(this.lastPlaying!==this.player.enabled){this.lastPlaying=this.player.enabled;for(const button of [this.$('music-toggle'),this.stageToggle]){button.textContent=this.player.enabled?'暂停音乐':'播放音乐';button.setAttribute('aria-pressed',String(this.player.enabled));}}}
}
