// Read-only explanations beside the real controls; they never change inference.
const explanations=[
 {id:'vision',target:'.workbench aside dl',title:'摄像头怎样看懂手？ · MediaPipe',body:'摄像头提供连续图片，MediaPipe Hand Landmarker 先找掌部区域，再估计手腕和指节等 21 个关键点。程序由点的位置计算弯曲、捏合与掌面方向。上方“当前追踪”和“单帧推理”显示实际运行结果；摄像头未开时不会产生识别数据。',extra:'YOLO 主要用于目标检测，也有姿态版本；本应用直接采用手部关键点方案，没有运行 YOLO。'},
 {id:'tracking',target:'#track-list',title:'角色怎样跟住同一只手？ · OC-SORT',body:'检测只回答这一帧手在哪里；跟踪要判断它刚才是哪只手。OC-SORT 把运动预测和当前观测结合，再做目标关联。应用另用位置、手形和短期外观线索维持角色编号，遮挡时先保留，分不清时用下面的绑定按钮。',extra:'经典 SORT 使用卡尔曼预测与匈牙利匹配。OC-SORT 改进了观测与关联方式。本机服务不可用时，页面会标明回退到浏览器轻量追踪；十只手是配置上限。'},
 {id:'motion',target:'.finger-controls',title:'点怎样变成动作？ · 几何映射与平滑',body:'用掌部尺度归一化距离，减小远近变化的影响；用骨节夹角与骨链比例估计弯曲。五根手指对应影人的头和四肢，掌心位置映射到舞台。翻面看掌面的方向。',extra:'指数平滑把上一时刻与当前测量加权：更平稳通常也更迟缓。滑块可直接试关节，摄像头模式才读取真实手指。'},
 {id:'props',target:'#scene-status',title:'拿起、放下怎样触发？ · 状态机',body:'手先靠近物件，再持续收拢，才进入“持有”；明确张开后进入“放下”。物件绑定角色实际渲染出的手腕，每件物件同时只归一只手。半握和短暂遮挡时先维持状态。',extra:'捏合使用不同的进入、退出门槛（滞回），动作还要经过持续时间与冷却判断，减少抖动造成的反复触发。'},
 {id:'learning',target:'#learn-prediction',title:'采样后学到了什么？ · kNN',body:'把手指伸展和捏合等量组成一个特征向量，与已标记样本比较距离，让最近的邻居投票，再参考最近几帧结果。太远、太混淆或票数分散时，保持“未知”。',extra:'这里学习的是关键点上的动作分类，没有重新训练 MediaPipe。连续采到的二十帧也不等于二十个独立人的测试。'},
 {id:'stt',target:'#drama-engine',title:'录音怎样变成文字？ · STT / SenseVoice',body:'STT 是 Speech-to-Text（语音转文字）。录音整理成 16 kHz 单声道，再由 SenseVoice Small 根据声音特征推测词句。台词与识别结果分开保留，方便回听核对。',extra:'音量、噪声和口音都会影响转写。录音时停止示范和配乐；声音不可用时提示重录，不计零分。'},
 {id:'tts',target:'#drama-tts-mount',title:'示范朗读从哪里来？ · TTS',body:'TTS 是 Text-to-Speech（文字转语音）。从词、标点和语速设置形成读音、时长与停顿，再合成声音。本应用使用 Windows 本机 System.Speech，具体可选声音以朗读设置为准。',extra:'同一句可重复听，也可放慢后再试。示范读音还需要教师核对；模型不会因为能合成语音，就自动判断孩子的发音。'},
 {id:'score',target:'#drama-feedback',title:'两个分数分别比较什么？ · 词与音素',body:'“台词匹配”用编辑距离比较转写与剧本：少词、多词和替换词分别记录。“发音参考”由独立 Wav2Vec2 音素模型从声音估计音素，用 CTC 合并重复并移除空白，再与词典中的候选读音比较。',extra:'转写对上不等于发音正确；音素相似度也不是经过儿童标定的发音正确率。蓝字门槛只改变鼓励提示，不改变分数。回听后选一个地方，再试一遍。'},
 {id:'music',target:'.music-bar',title:'配乐怎样写成可看的谱？ · YuE2',body:'YuE2 先生成旋律与和声的符号谱，再把审过的谱转成声音。配器和留白写进编曲说明；谱面试奏与模型生成的成品分别试听。',extra:'四段 YuE2 国乐配乐已完成听审，并保存在游戏本地。选曲、音量和随角色切换都在这里操作，播放不依赖配乐工作台或 DGX Spark。',link:'../audio/music/README.md',linkLabel:'配乐制作记录'}
];
const mounted=new Set();
function mount(){for(const item of explanations){if(mounted.has(item.id))continue;const target=document.querySelector(item.target);if(!target)continue;const detail=document.createElement('details');detail.className='principle-note';detail.id='principle-'+item.id;const summary=document.createElement('summary');summary.textContent=item.title;detail.append(summary);for(const value of [item.body,item.extra]){const p=document.createElement('p');p.textContent=value;detail.append(p)}if(item.link){const p=document.createElement('p'),a=document.createElement('a');a.href='http://127.0.0.1:8874/';a.target='_blank';a.rel='noopener';a.textContent=item.linkLabel;p.append(a);detail.append(p)}target.insertAdjacentElement('afterend',detail);mounted.add(item.id)}}
mount();if(mounted.size<explanations.length){const observer=new MutationObserver(()=>{mount();if(mounted.size===explanations.length)observer.disconnect()});observer.observe(document.querySelector('main'),{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),10000)}
